version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}  # Use Dockerfile.prod by default, but allow override with DOCKERFILE environment variable
    ports:
      - "3001:3001"
    volumes:
      - ./src:/app/src
